name: akash_portfolio
description: Professional Portfolio Website for Akash Anumolu - Full Stack Developer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # UI/UX - Using older version for compatibility
  responsive_framework: ^1.5.1
  flutter_staggered_grid_view: ^0.7.0  # Using older version
  flutter_staggered_animations: ^1.1.1
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  
  # Animations
  animated_text_kit: ^4.2.2
  animations: ^2.0.8
  # countup: ^0.1.4  # This package might not be available, remove if causing issues
  particles_flutter: ^1.0.1
  
  # Charts & Visualization
  fl_chart: ^1.1.1
  
  # Utilities
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  
  # Forms
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets - Commented out until directories are created
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # Fonts - Commented out until font files are added
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700